### ISSUE TITLE
Parsing of the mime types data on Ubuntu Trusty fails

### ISSUE THREAD

**Issue by jellybob** [mimemagicrb/mimemagic#106]
OS: ubuntu trusty 14.04.3 LTS
 shared-mime-info: 1.2-0ubuntu3

 ```
 $ bundle exec pry
 1:(main)> require 'mimemagic'
 SyntaxError: (eval):1: unterminated string meets end of file
 from /home/ubuntu/code/rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/mimemagic-0.3.7/lib/mimemagic/tables.rb:29:in `eval'
 ```

 ```
 $ apt list | grep shared-mime-info
 WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.
 shared-mime-info/trusty,now 1.2-0ubuntu3 amd64 [installed]
 ```

**Comment by jellybob** [comment]
@aristocrates this is the issue you raised.

**Comment by onyxraven** [comment]
Just ran across this too, (parallel issues!) in #108

**Comment by fredx** [comment]
I'm getting this issue too; tried 0.3.7 and 0.3.8. 

This regression is blocking our deployment, since the version that we were using 0.3.5 was yanked. 

THIS IS URGENT. PLEASE FIX.

**Comment by fredx** [comment]
@jellybob I suggest modifying the title of this issue to remove Ubuntu Trusty -- it's a cross-platform issue.

**Comment by Rozan-Mustafa** [comment]
I also tried all versions of mimemagic, bundle install fails on deploy with capistrano, it keeps telling:

> Your bundle is locked to mimemagic (0.3.5), but that version could not be found
> in any of the sources listed in your Gemfile. If you haven't changed sources,
> that means the author of mimemagic (0.3.5) has removed it. You'll need to update
> your bundle to a version other than mimemagic (0.3.5) that hasn't been removed
> in order to install.

**Comment by jellybob** [comment]
This should be resolve in 0.3.9 and 0.4.2, which have just been released.

**Comment by fredx** [comment]
Thank you!
