### ISSUE TITLE
Indicate the required version of the package/database (it requires >= 2.0)

### ISSUE THREAD

**Issue by onyxraven** [mimemagicrb/mimemagic#108]
The format of the XML file changed enough for xdg to [release a 2.0 in june of 2020](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases/2.0). 

OSs which may have a database that has not updated since then will likely install a 1.x release (say, 1.2 in Ubuntu trusty), which will fail with a hard-to-decode error

```
SyntaxError: (eval):1: unterminated string meets end of file
gems/mimemagic-0.3.7/lib/mimemagic/tables.rb:29:in `eval'
gems/mimemagic-0.3.7/lib/mimemagic/tables.rb:29:in `block (2 levels) in get_matches'
gems/mimemagic-0.3.7/lib/mimemagic/tables.rb:29:in `gsub!'
gems/mimemagic-0.3.7/lib/mimemagic/tables.rb:29:in `block in get_matches'
```

Installing the dpkg directly from the source (the download link in the README) does resolve this. But, it was not obvious that this was required.

Perhaps, this restriction needs added to the README and/or other documentation. It would also be great if the parser detected this early when possible.

**Comment by jellybob** [comment]
:+1: Thanks, I was going to dig into what was going on with the version in Trusty this evening, this will make that much easier. I'll do something about the error message instead.

**Comment by danilogco** [comment]
@jellybob please stop deleting versions in rubygems.org, please. I'm having problems with projects breaking unnecessarily...

**Comment by jellybob** [comment]
We have stopped yanking versions now that none of them come with legal issues. 3.0.7 onwards are stable, and will remain in place. Also, please stop spamming unrelated issues.

**Comment by pixeltrix** [comment]
@jellybob you should be aware that v2 only appears in Ubuntu 20.04 and Debian Unstable (Sid) - asking people to download a .deb and extract a file isn't really going to work for servers that have to autoscale.

**Comment by onyxraven** [comment]
> @jellybob you should be aware that v2 only appears in Ubuntu 20.04 and Debian Unstable (Sid) - asking people to download a .deb and extract a file isn't really going to work for servers that have to autoscale.

I was able to install the dpkg directly on trusty after downloading the deb with wget (using dpkg -i). It's not ideal but works until we can bake it into our base image. This is also doable with a tool like chef using a `remote_file` and `dpkg_package` pair.

**Comment by pixeltrix** [comment]
Also going to break on anything less than a Heroku-20 stack by the looks of it

**Comment by kwong-yw** [comment]
> Also going to break on anything less than a Heroku-20 stack by the looks of it

From my understanding, Heroku-20 only has `shared-mime-info` 1.15-1 installed as per [this article](https://devcenter.heroku.com/articles/stack-packages), so even on the latest stack, one would probably have to use https://github.com/heroku/heroku-buildpack-apt to specifically install v2.

**Comment by schneems** [comment]
@kwong-yw is correct. That article accurately lists current versions. A co-worker @dzuelke pointed out that 20.04 is the current Ubuntu LTS, and the next one will not land until 2022. The mimemagic Gem will likely need to support both the v1 and v2 XML formats if it wants to use this package.

**Comment by dzuelke** [comment]
Even Focal, the current Ubuntu LTS (20.04) has v1.1.5: https://packages.ubuntu.com/focal/shared-mime-info

The next Ubuntu LTS won't land until April 2022, and there are plenty (read: millions, billions, who knows these days with the cloud and all) servers around with v1.x shared-mime-info, and for years to come - the report in #106 is from someone still running 14.04, which has been EOL for two years!

So it looks like it'll be unavoidable for the Gem to support both v1 and v2 XML formats.

I looked at the failing line:

```Ruby
value.gsub!(/\\(x[\dA-Fa-f]{1,2}|0\d{1,3}|\d{1,3}|.)/) { eval("\"\\#{$1}\"") }
```

So in some element in the v2 format, that regex doesn't match, leading the `eval` to fail.

Aside from the obvious question of whether `eval`ing parts of a file from the filesystem is a good idea ;), this doesn't seem to be an unsolvable issue. I did compare the formats for a bit but couldn't straight away identify what string in the v2 file caused the failure; maybe someone else who already has a reproduce sample can provide that.

**Comment by onyxraven** [comment]
Agree. The gem was able to ignore the version difference before the change, because it could always bundle the appropriate version. Now, it will need to support multiple versions. At this point I haven't looked back in history to see how the XML handler has evolved, but perhaps there is existing code in an older revision that can help here.

**Comment by dzuelke** [comment]
Alright, found the issue.

IT IS NOT A 2.0 ISSUE. The diff between 1.15 and 2.0 is actually minimal.

It breaks with version 1.9, but not with version 1.15.

That means Ubuntu 20.04 is in the clear, and Ubuntu 18.04 for instance is affected.

I'll spare you the full diff, let's just focus on what matters:

```Diff
# diff -u <(grep 'type="string"' bionic/usr/share/mime/packages/freedesktop.org.xml) <(grep 'type="string"' focal/usr/share/mime/packages/freedesktop.org.xml) | grep eval
-      <match value='eval \"exec /bin/gjs' type="string" offset="0"/>
-      <match value='eval \"exec /usr/bin/gjs' type="string" offset="0"/>
-      <match value='eval \"exec /usr/local/bin/gjs' type="string" offset="0"/>
+      <match type="string" value="eval \&quot;exec /bin/gjs" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/bin/gjs" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/local/bin/gjs" offset="0"/>
-      <match value='eval \"exec /usr/local/bin/perl' type="string" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/local/bin/perl" offset="0"/>
-      <match value='eval \"exec /bin/python3' type="string" offset="0"/>
-      <match value='eval \"exec /usr/bin/python3' type="string" offset="0"/>
-      <match value='eval \"exec /usr/local/bin/python3' type="string" offset="0"/>
-      <match value='eval \"exec /bin/python' type="string" offset="0"/>
-      <match value='eval \"exec /usr/bin/python' type="string" offset="0"/>
-      <match value='eval \"exec /usr/local/bin/python' type="string" offset="0"/>
+      <match type="string" value="eval \&quot;exec /bin/python3" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/bin/python3" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/local/bin/python3" offset="0"/>
+      <match type="string" value="eval \&quot;exec /bin/python" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/bin/python" offset="0"/>
+      <match type="string" value="eval \&quot;exec /usr/local/bin/python" offset="0"/>
```

The `value` string is `eval`ed, and if that string is `eval \"something`, then, well...:

```
irb(main):008:0> value='eval \"exec /bin/gjs'
=> "eval \\\"exec /bin/gjs"
irb(main):009:0> value.gsub!(/\\(x[\dA-Fa-f]{1,2}|0\d{1,3}|\d{1,3}|.)/) { eval("\"\\#{$1}") }
Traceback (most recent call last):
        7: from /usr/bin/irb:23:in `<main>'
        6: from /usr/bin/irb:23:in `load'
        5: from /Library/Ruby/Gems/2.6.0/gems/irb-1.0.0/exe/irb:11:in `<top (required)>'
        4: from (irb):9
        3: from (irb):9:in `gsub!'
        2: from (irb):9:in `block in irb_binding'
        1: from (irb):9:in `eval'
SyntaxError ((eval):1: unterminated string meets end of file)
```

Lesson: don't parse things with eval ;)

**Comment by jellybob** [comment]
@dzuelke thank you, that's really useful information. From the look of it this should be relatively simple to resolve, I'm not at all familiar with the guts of the parsing that's going on, but it does seem that not `eval`ing things is going to go a long way, I think that's just a legacy of the original approach of dumping everything out to generated Ruby.

**Comment by dzuelke** [comment]
Note: it just happens to be that the string that's failing also contains the string "eval", but that is unrelated - all that it takes is any quotes in the string. Escaping might work.

This does beg the question though - why is this not happening on 1.15?

After all, the attribute value of `value` in this:

```
value="eval \&quot;exec /bin/python3"
```

gets returned by the XML parser as this:

```
eval \"exec /bin/python3
```

Which should again trigger the problem.

Is the XML parsing also broken, maybe? It must be if the above string isn't triggering the problem, unless the code is (incorrectly!) accessing the raw attribute node value rather than its parsed representation.

**Comment by tmr08c** [comment]
We have been testing this in a few different environments and wanted to include our findings. 

So far, we have been able to **successfully** parse the DB file with the following combinations of OS and `shared-mime-info` packages. We haven't done an exhaustive `bisect` or anything, but, our tests pass and our applications are booting successfully. 

This was tested with `v0.3.8` of `mimemagic`.


| OS                              | shared-mime-info Version                                             |
|---------------------------------|----------------------------------------------------------------------|
| macOS                           | 2.1                                                                  |
| Ubuntu 18 (via Docker)          | shared-mime-info/now 1.9-2 amd64 [installed,local]                   |
| Ubuntu 16.04 (via AWS OpsWorks) | shared-mime-info/xenial-updates,now 1.5-2ubuntu0.2 amd64 [installed] |
| Ubuntu 16.04 (via Docker)       | 1.5-2ubuntu0.2                                                       |

**Comment by dzuelke** [comment]
Yeah, follow up, I looked at this again - the way the `eval` actually works shouldn't even be affected by the quotes I pulled as an example.

Is this maybe a Ubuntu 14.04-only problem?

(Should still not crash there obviously).

**Comment by jellybob** [comment]
I'm doing some testing against the specific version of the fd.o.xml mentioned in the original issue report, and it appears to be blowing up at the element `<match value="\chapter" type="string" offset="0:100"/>`, and only that element - commenting it out results in a successful run of the unit tests.

**Comment by jellybob** [comment]
What's getting `eval`ed here after the regex replacement is `"\"\\c\""`, which for some reason which isn't at all clear to me right now does indeed throw an unterminated string error if you call `eval("\"\\c\"")`.

**Comment by jellybob** [comment]
Sorry for the rapid fire comments, I'm at least partially talking to myself here.

That string is interpreted as `"\c"` - `\c"` is the literal for the control character `"`, which... isn't hugely useful. So yes, this is an issue with badly escaped characters. For the sake of getting this working in the one case it's known to cause problems I'm inclined to just hack something in so that `\c` gets rewritten to `\\c` before it's interpreted. Not clean, but it gets things moving again, and I don't really have the energy at this point to find a better solution.

**Comment by ssnyder** [comment]
starting from the Ruby:2.4.3 image, I get the error mentioned above when running my CI/CD pipeline to run my tests. I have confirmed that version 0.3.8 is being installed and the following error occurs when I run: bundle exec rails db:create db:schema:load db:migrate --trace

Here is the complete error that I get (in case it helps someone):

> rails aborted!
SyntaxError: (eval):1: unterminated string meets end of file
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:29:in `eval'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:29:in `block (2 levels) in get_matches'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:29:in `gsub!'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:29:in `block in get_matches'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:19:in `map'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:19:in `get_matches'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:77:in `block (2 levels) in parse_database'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:75:in `block in parse_database'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:238:in `block in each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `upto'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/nokogiri-1.10.10/lib/nokogiri/xml/node_set.rb:237:in `each'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic/tables.rb:70:in `parse_database'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/mimemagic-0.3.8/lib/mimemagic.rb:8:in `<top (required)>'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `block in require'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:258:in `load_dependency'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/activesupport-5.1.7/lib/active_support/dependencies.rb:292:in `require'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/axlsx-3.0.0.pre/lib/axlsx.rb:4:in `<top (required)>'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:81:in `block (2 levels) in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:76:in `block in require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `each'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler/runtime.rb:65:in `require'
/usr/local/lib/ruby/site_ruby/2.4.0/bundler.rb:114:in `require'
/builds/research/datateam/dovecote/annotation_configurator/config/application.rb:7:in `<top (required)>'
/builds/research/datateam/dovecote/annotation_configurator/Rakefile:4:in `require_relative'
/builds/research/datateam/dovecote/annotation_configurator/Rakefile:4:in `<top (required)>'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/rake_module.rb:29:in `load_rakefile'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:703:in `raw_load_rakefile'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:104:in `block in load_rakefile'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:103:in `load_rakefile'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/railties-5.1.7/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/railties-5.1.7/lib/rails/command.rb:46:in `invoke'
/builds/research/datateam/dovecote/annotation_configurator/vendor/ruby/2.4.0/gems/railties-5.1.7/lib/rails/commands.rb:16:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

**Comment by schneems** [comment]
🎉🎉🎉 thanks for all the work here!

**Comment by dzuelke** [comment]
Nice job, @jellybob, I didn't have a quick reproduce case on hand.

I should note that 20.04's version doesn't have that value anymore at all.

In 18.04 and 16.04, it's double backslash escaped:

```
<match value="\\chapter" type="string" offset="0:100"/>
```

In 14.04, it's got a single backslash:

```
<match value="\\chapter" type="string" offset="0:100"/>
```

So it looks like it's indeed only the EOL Ubuntu 14.04 that's affected in the first place.

**Comment by onyxraven** [comment]
@jellybob thanks again!
