### ISSUE TITLE
This is the second time you removed branch !!!!!

### ISSUE THREAD

**Issue by hamdallahjoudah** [mimemagicrb/mimemagic#116]
Please why you did this???

**Comment by mansoorelahi** [comment]
it's not straightforward to upgrade to  0.4.x version either :(

**Comment by yusufali94** [comment]
why are versions being yanked?

**Comment by rylanb** [comment]
More info here: https://github.com/rails/rails/issues/41750

https://github.com/jellybob/mimemagic/issues/2
https://github.com/jellybob/mimemagic/pull/3
