### ISSUE TITLE
Allow installation of this gem on systems without freedesktop.xml

### ISSUE THREAD

**Issue by Scharrels** [mimemagicrb/mimemagic#118]
A lot of projects have this gem as a dependency, but are not actually using it. The post-install checks in the newest versions of this script make it impossible to build these projects, without providing a freedesktop.xml file.

This can be a problem for multiple reasons:
* If your project is providing a docker image, then your project might be forced to deal with the licensing issues that were solved in the latest versions of this gem
* Your operating system might not provide the right version of this file, forcing you to include a file that you download manually from the internet
* A user that is fairly new to ruby and tries to install Rails will have trouble installing a basic development environment: all basic tutorials will fail, and changes are that troubleshooting will scare off such a user.

Is it possible to provide some means to skip the installation part, and just install this gem without activating it?

A couple of suggestions:
* Provide an environment variable that people can use to indicate that they do not wish to use any freedesktop.xml
* Provide a dummy freedesktop.xml that conforms to the format that this gem needs, but does not have any actual content

**Comment by kaspergrubbe** [comment]
I would prefer things like these to blow up on install rather than during runtime.

**Comment by Scharrels** [comment]
That's exactly why I suggest to use an environment variable to disable installation. The default can still be to blow up on install, but such a solution can provide an alternative for the people that know that this library will not be used, but are unable to install any freedesktop.xml file.

**Comment by jellybob** [comment]
If you're really not using this gem in your project you can explicitly remove the dependency Rails has on ActiveStorage in your Gemfile to do so. I'm not hugely comfortable with introducing an environment variable that explicitly breaks the gem during its installation process, especially given Rails' dependency is short lived due to work the Rails core team are doing to move away from it.

I'm going to sleep on this and see how I feel tomorrow, so will leave it open for now.

**Comment by Scharrels** [comment]
I would have agreed with you, if this would just affect ActiveStorage. As of now, this gem leaks into projects via many gems. To name two popular ones:

* Cucumber-rails: the main release includes rails, instead of railties (people are working on a new release to fix this in https://github.com/cucumber/cucumber-rails/issues/494)
* Community axlsx: This library is used to determine the mime type of embedded objects in an excel file. A lot of users will not use embedded objects at all, but are now forced to deal with this situation, until this gem moves on to a different solution. It seems that this project is waiting on Rails for this: https://github.com/caxlsx/caxlsx/issues/92

I don't think that it's a good idea to break this gem in the long term. I'm mainly looking for a solution to get current projects up and running, for people that did not choose to include this dependency, but are somehow forced to deal with it, until these (and probably some other) libraries have dealt with this situation.

Perhaps we can compromise on a solution that allows a smoother transition until this situation is resolved, while not affecting this project in the long run.

Semantic versioning might help us out with this. We could introduce an environment variable (or some other override) in version 0.3.x, allowing people to resolve the problems in current builds, and deprecate it immediately, by not introducing it in 0.4.x. This allows people to override it now, while leaving it out of the rest of the releases.

Would this satisfy your concerns?

**Comment by mvz** [comment]
I think you can just create a dummy xml file and point the gem to it during installation, like so:

```
touch dummy.xml
FREEDESKTOP_MIME_TYPES_PATH=dummy.xml gem install mimemagic
```

**Comment by jellybob** [comment]
@Scharrels sure, I think that works. Are you able to open a PR implementing that?

**Comment by tetienne** [comment]
@mvz Your suggested workaround does not work in my case and for my teammates. 

```
❯ touch dummy.xml
❯ FREEDESKTOP_MIME_TYPES_PATH=dummy.xml gem instal mimemagic -v '0.3.7'           
Building native extensions. This could take a while...
ERROR:  Error installing mimemagic:
        ERROR: Failed to build gem native extension.

    current directory: /Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mimemagic-0.3.7/ext/mimemagic
/Users/tetienne/.rbenv/versions/2.7.1/bin/ruby -I/Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/2.7.0/rubygems -rrubygems /Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/rake-13.0.3/exe/rake RUBYARCHDIR\=/Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/mimemagic-0.3.7 RUBYLIBDIR\=/Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/mimemagic-0.3.7
rake aborted!
Could not find MIME type database in the following locations: ["/Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mimemagic-0.3.7/ext/mimemagic/dummy.xml", "/usr/local/share/mime/packages/freedesktop.org.xml", "/opt/homebrew/share/mime/packages/freedesktop.org.xml", "/usr/share/mime/packages/freedesktop.org.xml"]

Ensure you have either installed the shared-mime-types package for your distribution, or 
obtain a version of freedesktop.org.xml and set FREEDESKTOP_MIME_TYPES_PATH to the location 
of that file.

Tasks: TOP => default
(See full trace by running task with --trace)

rake failed, exit code 1

Gem files will remain installed in /Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/mimemagic-0.3.7 for inspection.
Results logged to /Users/tetienne/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/mimemagic-0.3.7/gem_make.out
```

**Comment by jellybob** [comment]
@tetienne you'll need to give a full path to the file, and make sure its in a place it won't get removed from at runtime since that file is going to be opened on loading mimemagic. I'm not 100% an empty file will work, but you could almost certainly get away with:

```
<?xml version="1.0" encoding="UTF-8"?>
<mime-info>
</mime-info>
```

**Comment by Scharrels** [comment]
I already confirmed it over here: the empty file works during install time, as long as you provide the full path. I've almost completed the skip option.

**Comment by tetienne** [comment]
@jellybob Many thx. I was able to fix my project installation.

**Comment by Scharrels** [comment]
I have built the PR. I have put the explanation in a different commit. Feel free to modify that one as you see fit.

I don't know how to test this kind of build task. I would recommend a quick test to see if I didn't make any typos, before releasing, if the CI does not do this.

**Comment by jellybob** [comment]
You can test with:

`gem build mimemagic.gemspec && gem install mimemagic-*.gem` then poke at things via irb. At some point I'll get round to something a little more robust :)

**Comment by Scharrels** [comment]
Well, it needed a little fix: I messed up the path to the dummy xml. This is fixed, now.

I have tried to a couple of variants in this part of the readme:

https://github.com/mimemagicrb/mimemagic#usage

It seems that all responses are `nil` which is to be expected if the database is empty.
