### ISSUE TITLE
PLEASE KEEP OLD VERSION!!!!!!!

### ISSUE THREAD

**Issue by toantt28** [mimemagicrb/mimemagic#127]
Please keep old versions when you release new version.
My rails app always fail from yesterday when Gemfile.lock has not been updated, start from 0.3.5 and then 0.3.6

Many Thanks.

**Comment by rstacruz** [comment]
Unfortunately this isn't possible because of legal licensing issues. It also isn't possible to push new code in place of the old versions.

- https://www.theregister.com/2021/03/25/ruby_rails_code/
- https://github.com/rails/rails/issues/41750
