### ISSUE TITLE
Version 0.3.5 could not be found

### ISSUE THREAD

**Issue by gmcquistin** [mimemagicrb/mimemagic#139]
Hi,

We are getting this error during `bundle install`:

>Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.5) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.5) that hasn't been removed in order to install.

Was this version removed on purpose?

Thanks

**Comment by thadeubrito** [comment]
https://github.com/rails/rails/issues/41757

**Comment by epugh** [comment]
Thanks for opening this issue, this helped us track down our issue.

**Comment by gmcquistin** [comment]
Thanks for the link @thadeubrito 🙂 

We hit this issue because Rails depended indirectly on mimemagic. It looks like the latest Rails releases[0] remove this dependency altogether - this resolves our problem

Thanks all!

[0] https://weblog.rubyonrails.org/2021/3/26/marcel-upgrade-releases/

**Comment by drewB** [comment]
For anyone else running into this thought I would be more explicit about how to fix. 

Option 1: Update to your lastest version of rails (back to 5.2, 6.0, 6.1).  `bundle update rails`
Option 2: Update your version of mimemagic.  `bundle update mimemagic`

**Comment by flutterq** [comment]
[[Solved] Your bundle is locked to mimemagic (0.3.5), but that version could not be found in any of the sources listed in your Gemfile
](https://exerror.com/your-bundle-is-locked-to-mimemagic-0-3-5-but-that-version-could-not-be-found/)
